### ISSUE TITLE
Changelog issue

### ISSUE THREAD

**Issue by crayxt** [asv/deadbeef-debian#2]
Why it is 
"deadbeef (v0.5.2-1) UNRELEASED; urgency=low", previous ones were just
deadbeef (0.5.1-1) and so on. e.g. without 'v' letter in version.

Shouldn't it be just "deadbeef (0.5.2-1)"?

**Comment by vasiliyl** [comment]
Same here:

```
> LC_ALL=C dpkg-buildpackage -rfakeroot -us -uc -i -I".git" 
parsechangelog/debian: warning:     debian/changelog(l1): version 'v0.5.2-1' is invalid: version number does not start with digit
LINE: deadbeef (v0.5.2-1) UNRELEASED; urgency=low
dpkg-buildpackage: source package deadbeef
dpkg-buildpackage: source version v0.5.2-1
dpkg-buildpackage: error: version number does not start with digit
```

After removing `v' from version all goes fine.

**Comment by crayxt** [comment]
By the way, deadbeef is already in debian-multimedia repo.
But it requires many packages to be installed from the debian-multimedia repo.

**Comment by asv** [comment]
Fixed. Thanks for bug report.
